default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  user: postgres
  password: postgres

development:
  <<: *default
  database: rails-base-test

test:
  <<: *default
  database: rails-base-test

production:
  <<: *default
  host: PROJECT_NAME-db
  database: <%= ENV['DATABASE_NAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  user: <%= ENV['POSTGRES_USER'] %>
