# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StylesConfigsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # StylesConfig. As you add validations to StylesConfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StylesConfigsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all styles_configs as @styles_configs' do
      styles_config = StylesConfig.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:styles_configs)).to eq([styles_config])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested styles_config as @styles_config' do
      styles_config = StylesConfig.create! valid_attributes
      get :show, params: { id: styles_config.to_param }, session: valid_session
      expect(assigns(:styles_config)).to eq(styles_config)
    end
  end

  describe 'GET #new' do
    it 'assigns a new styles_config as @styles_config' do
      get :new, params: {}, session: valid_session
      expect(assigns(:styles_config)).to be_a_new(StylesConfig)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested styles_config as @styles_config' do
      styles_config = StylesConfig.create! valid_attributes
      get :edit, params: { id: styles_config.to_param }, session: valid_session
      expect(assigns(:styles_config)).to eq(styles_config)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new StylesConfig' do
        expect do
          post :create, params: { styles_config: valid_attributes }, session: valid_session
        end.to change(StylesConfig, :count).by(1)
      end

      it 'assigns a newly created styles_config as @styles_config' do
        post :create, params: { styles_config: valid_attributes }, session: valid_session
        expect(assigns(:styles_config)).to be_a(StylesConfig)
      end

      it 'verifies if the newly created styles_config is persisted' do
        post :create, params: { styles_config: valid_attributes }, session: valid_session
        expect(assigns(:styles_config)).to be_persisted
      end

      it 'redirects to the created styles_config' do
        post :create, params: { styles_config: valid_attributes }, session: valid_session
        expect(response).to redirect_to(StylesConfig.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved styles_config as @styles_config' do
        post :create, params: { styles_config: invalid_attributes }, session: valid_session
        expect(assigns(:styles_config)).to be_a_new(StylesConfig)
      end

      it "re-renders the 'new' template" do
        post :create, params: { styles_config: invalid_attributes }, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested styles_config' do
        styles_config = StylesConfig.create! valid_attributes
        put :update, params: { id: styles_config.to_param, styles_config: new_attributes }, session: valid_session
        styles_config.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested styles_config as @styles_config' do
        styles_config = StylesConfig.create! valid_attributes
        put :update, params: { id: styles_config.to_param, styles_config: valid_attributes }, session: valid_session
        expect(assigns(:styles_config)).to eq(styles_config)
      end

      it 'redirects to the styles_config' do
        styles_config = StylesConfig.create! valid_attributes
        put :update, params: { id: styles_config.to_param, styles_config: valid_attributes }, session: valid_session
        expect(response).to redirect_to(styles_config)
      end
    end

    context 'with invalid params' do
      it 'assigns the styles_config as @styles_config' do
        styles_config = StylesConfig.create! valid_attributes
        put :update, params: { id: styles_config.to_param, styles_config: invalid_attributes }, session: valid_session
        expect(assigns(:styles_config)).to eq(styles_config)
      end

      it "re-renders the 'edit' template" do
        styles_config = StylesConfig.create! valid_attributes
        put :update, params: { id: styles_config.to_param, styles_config: invalid_attributes }, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested styles_config' do
      styles_config = StylesConfig.create! valid_attributes
      expect do
        delete :destroy, params: { id: styles_config.to_param }, session: valid_session
      end.to change(StylesConfig, :count).by(-1)
    end

    it 'redirects to the styles_configs list' do
      styles_config = StylesConfig.create! valid_attributes
      delete :destroy, params: { id: styles_config.to_param }, session: valid_session
      expect(response).to redirect_to(styles_configs_url)
    end
  end
end
